# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d137d460ce67768c33e94f6166e735fc8ec2b8e71a7a92145d03571ec9bc06916ab8709f2efff6765de58a18137b861f526e2423608d25cae3eddba64146c0b9

test:
  secret_key_base: 9eb5597e4a4e5ab913ec3f1330438dd531b84c8691f1ccce39e664f7f0eecb6e92700ca9be37061d5154a0d4934599132ee840027f0ffd0d4432553cc9d692aa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
